import { formatMoney } from "../../engine/game-engine.js";
import { getEncyclopediaSeasons, getEncyclopediaSeason, getWorldRanking, getPlayerBiography, getEncyclopediaRecords, getHallMuseum, getEncyclopediaDashboard, getDraftArchive, getCompetitionArchive, getClubArchive, getClubBiography, getNationalTeamArchive, getTimelineArchive, searchEncyclopedia } from "../../engine/encyclopedia-engine.js";
import { diagnoseGame } from "../../engine/health-engine.js";
import { getSaveMeta, hasBackup } from "../../engine/persistence-engine.js";
import { getBalanceReport } from "../../engine/beta-balance-engine.js";
export function createEncyclopediaViews(context){
  let game=null;
  let encyclopediaSeason=null;
  let encyclopediaPlayerId=null;
  let encyclopediaClubId=null;
  let encyclopediaSection=null;
  let encyclopediaQuery=null;
  let activeView=null;
  function sync(){({game,encyclopediaSeason,encyclopediaPlayerId,encyclopediaClubId,encyclopediaSection,encyclopediaQuery,activeView}=context.getState());}
  const playerHeader=()=>context.playerHeader();

function encyclopediaScreen(){
  const dashboard=getEncyclopediaDashboard(game),seasons=getEncyclopediaSeasons(game),ranking=getWorldRanking(game),records=getEncyclopediaRecords(game),hall=getHallMuseum(game),drafts=getDraftArchive(game),competitions=getCompetitionArchive(game),clubs=getClubArchive(game),nationalTeams=getNationalTeamArchive(game),timeline=getTimelineArchive(game),results=encyclopediaQuery?searchEncyclopedia(game,encyclopediaQuery):[];
  const nav=[['home','Inicio'],['seasons','Temporadas'],['players','Jugadores'],['drafts','Drafts'],['competitions','Competiciones'],['clubs','Clubes'],['teams','Selecciones'],['records','Récords'],['timeline','Cronología']];
  const header=`${playerHeader()}<section class="card encyclopedia-hero"><span class="pill">NBA GLORY 1.5.5</span><h2>Basketball Encyclopedia</h2><p class="muted">Toda la historia de tu universo en una base de datos navegable.</p><form id="encyclopediaSearch" class="encyclopedia-search"><input id="encyclopediaQuery" value="${encyclopediaQuery.replaceAll('"','&quot;')}" placeholder="Buscar jugador, club, campeón, temporada..."><button class="btn">Buscar</button></form><div class="encyclopedia-tabs">${nav.map(([id,label])=>`<button type="button" data-encyclopedia-section="${id}" class="${encyclopediaSection===id?'active':''}">${label}</button>`).join('')}</div></section>`;
  if(encyclopediaQuery){return header+`<section class="card"><div class="topline"><div><span class="pill">RESULTADOS</span><h3>${results.length} coincidencias para “${encyclopediaQuery}”</h3></div><button class="mini-btn" data-clear-encyclopedia-search>Limpiar</button></div><div class="database-list">${results.map(r=>`<button data-encyclopedia-result="${r.type}" data-result-id="${r.id}"><div><strong>${r.title}</strong><small>${r.subtitle}</small></div><span>${r.type}</span></button>`).join('')||'<p class="muted">No se encontraron resultados.</p>'}</div></section>`;}
  let body='';
  if(encyclopediaSection==='home')body=`<section class="card encyclopedia-dashboard"><h3>El universo en cifras</h3><div class="encyclopedia-kpis">${[['Temporadas',dashboard.stats.seasons],['Jugadores',dashboard.stats.players],['Drafts',dashboard.stats.drafts],['Clubes',dashboard.stats.clubs],['Selecciones',dashboard.stats.internationalTeams],['Hall of Fame',dashboard.stats.hallOfFamers]].map(([l,v])=>`<div><span>${l}</span><strong>${v}</strong></div>`).join('')}</div></section>${dashboard.latestSeason?seasonArchiveCard(dashboard.latestSeason):''}<section class="card"><h3>👑 Leyendas actuales</h3>${databasePlayers(dashboard.topPlayers)}</section><section class="card"><h3>🏟️ Clubes históricos</h3>${databaseClubs(dashboard.topClubs)}</section>`;
  if(encyclopediaSection==='seasons')body=`<section class="card"><h3>📅 Archivo de temporadas</h3><div class="season-archive-grid">${seasons.map(seasonArchiveCard).join('')||'<p class="muted">Completa temporadas para llenar el archivo.</p>'}</div></section>`;
  if(encyclopediaSection==='players')body=`<section class="card"><h3>🏀 Base de datos de jugadores</h3><p class="muted">Activos, estrellas europeas y retirados ordenados por legado.</p>${databasePlayers(ranking.slice(0,50))}</section><section class="card"><h3>🏛️ Hall of Fame</h3>${databasePlayers(hall.slice(0,30))}</section>`;
  if(encyclopediaSection==='drafts')body=`<section class="card"><h3>🎓 Archivo de Drafts</h3>${drafts.map(d=>`<article class="archive-block"><div class="topline"><div><strong>Draft ${d.season}</strong><small>Fuerza de clase ${d.classStrength||'—'} · NCAA ${d.champion||'—'}</small></div><span>${d.picks.length} jugadores</span></div><div class="draft-board">${d.picks.slice(0,10).map(p=>`<article><strong>#${p.pick}</strong><span>${p.name}</span><small>${p.country||''} · ${p.college||p.team||''} · ${p.grade||`POT ${p.potential||'—'}`}</small></article>`).join('')}</div></article>`).join('')||'<p class="muted">Aún no hay Drafts archivados.</p>'}</section>`;
  if(encyclopediaSection==='competitions')body=`<section class="card"><h3>🏆 Campeones NBA</h3>${competitionRows(competitions.nba,'NBA')}</section><section class="card"><h3>🇪🇺 Euroliga y ACB</h3>${competitionRows(competitions.europe,'Europa')}</section><section class="card"><h3>🎓 NCAA</h3>${competitionRows(competitions.ncaa,'NCAA')}</section><section class="card"><h3>🌍 FIBA</h3>${competitionRows(competitions.fiba,'FIBA')}</section>`;
  if(encyclopediaSection==='clubs')body=`<section class="card"><h3>🏟️ Enciclopedia de clubes</h3>${databaseClubs(clubs)}</section>`;
  if(encyclopediaSection==='teams')body=`<section class="card"><h3>🌍 Selecciones nacionales</h3><div class="database-list">${nationalTeams.map(t=>`<article><div><strong>#${t.ranking||'—'} ${t.name}</strong><small>${t.region} · Entrenador ${t.coach}<br>🥇 ${t.medals?.gold||0} · 🥈 ${t.medals?.silver||0} · 🥉 ${t.medals?.bronze||0}</small></div><span>${Math.round(t.points||0)}</span></article>`).join('')}</div></section>`;
  if(encyclopediaSection==='records')body=`<section class="card"><h3>📖 Libro de récords</h3><div class="record-grid">${records.map(r=>`<article class="record-card"><span class="muted small">${r.scope} · ${r.label}</span><strong>${formatNumber(r.value)}</strong><span>${r.holder}</span></article>`).join('')}</div></section>`;
  if(encyclopediaSection==='timeline')body=`<section class="card"><h3>🗓️ Cronología completa</h3><div class="timeline">${timeline.map(x=>`<div class="timeline-year"><div class="year-badge">${x.season}</div><div class="timeline-events"><article class="timeline-event"><span class="event-icon">${x.type==='FIBA'?'🌍':x.type==='Temporada'?'🏆':'🏀'}</span><div><strong>${x.title}</strong>${x.text?`<small>${x.text}</small>`:''}</div></article></div></div>`).join('')||'<p class="muted">La historia todavía no ha comenzado.</p>'}</div></section>`;
  return header+body+'<button data-view="league" class="btn secondary">🔥 Volver a Liga Viva</button>';
}
function seasonArchiveCard(entry){const fiba=entry.fiba?`<small>${entry.fiba.tournament}: ${entry.fiba.gold}</small>`:'';return `<button class="season-archive-card" data-encyclopedia-result="season" data-result-id="${entry.season}"><span>${entry.season}</span><strong>${entry.nba.champion}</strong><small>MVP ${entry.nba.mvp}</small><small>Europa: ${entry.europe.champion}</small><small>NCAA: ${entry.ncaa.champion}</small>${fiba}</button>`;}
function databasePlayers(players){return `<div class="database-list">${players.map((p,i)=>`<button data-universe-player="${p.id}"><div><strong>#${p.rank||i+1} ${p.name}</strong><small>${p.country} · ${p.position} · ${p.currentTeam}<br>${p.awards?.length||0} premios · ${p.status}</small></div><span>${p.legacyScore}</span></button>`).join('')||'<p class="muted">No hay jugadores disponibles.</p>'}</div>`;}
function databaseClubs(clubs){return `<div class="database-list">${clubs.map((c,i)=>`<button data-europe-club="${c.id}"><div><strong>#${i+1} ${c.name}</strong><small>${c.country} · ${c.league} · ${c.style}<br>${c.titles||0} Euroligas · ${c.domesticTitles||0} ligas · ${c.cups||0} copas</small></div><span>${c.score||c.prestige}</span></button>`).join('')}</div>`;}
function competitionRows(rows,type){return `<div class="database-list">${rows.map(r=>`<article><div><strong>${r.season} · ${r.champion||r.gold}</strong><small>${type==='NBA'?`Finalista ${r.finalist} · MVP ${r.mvp}`:type==='Europa'?`Finalista ${r.finalist} · MVP ${r.mvp} · ACB ${r.acbChampion}`:type==='NCAA'?`MOP ${r.mop} · Jugador del Año ${r.playerOfYear}`:`${r.tournament} · Plata ${r.silver} · MVP ${r.mvp}`}</small></div><span>${type}</span></article>`).join('')||'<p class="muted">Sin registros todavía.</p>'}</div>`;}

function playerBiographyScreen(){
 const p=getPlayerBiography(game,encyclopediaPlayerId); if(!p){context.setActiveView('encyclopedia');activeView='encyclopedia';return encyclopediaScreen();}
 return `<section class="card biography-hero"><div class="bio-avatar">${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><span class="pill">PERFIL HISTÓRICO</span><h2>${p.name}</h2><p class="muted">${p.country} · ${p.position} · ${p.status} · ${p.currentTeam}</p><div class="grid"><div class="stat"><span class="muted small">OVR</span><strong>${p.ovr}</strong></div><div class="stat"><span class="muted small">POTENCIAL</span><strong>${p.potential}</strong></div><div class="stat"><span class="muted small">LEGACY</span><strong>${p.legacyScore}</strong></div><div class="stat"><span class="muted small">PREMIOS</span><strong>${p.awards.length}</strong></div></div></section><section class="card"><h3>Biografía</h3><p class="result">${p.summary}</p></section><section class="card"><h3>🏆 Palmarés</h3>${p.awards.map(a=>`<p class="pathway-achievement">🏆 ${a}</p>`).join('')||`<p class="muted">Todavía no ha ganado premios principales.</p>`}</section><section class="card"><h3>📅 Trayectoria</h3><div class="timeline">${p.timeline.map(x=>`<div class="timeline-year"><div class="year-badge">${x.season}</div><div class="timeline-events"><article class="timeline-event"><span class="event-icon">🏀</span><div><strong>${x.text}</strong></div></article></div></div>`).join('')}</div></section><button data-view="encyclopedia" class="btn">← Volver a la Enciclopedia</button>`;
}


function clubBiographyScreen(){
 const c=getClubBiography(game,encyclopediaClubId);if(!c){context.setActiveView('encyclopedia');activeView='encyclopedia';return encyclopediaScreen();}
 return `<section class="card biography-hero"><div class="bio-avatar">${c.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><span class="pill">CLUB HISTÓRICO</span><h2>${c.name}</h2><p class="muted">${c.country} · ${c.league} · ${c.style}</p><div class="grid"><div class="stat"><span class="muted small">PRESTIGIO</span><strong>${c.prestige}</strong></div><div class="stat"><span class="muted small">EUROLIGAS</span><strong>${c.titles}</strong></div><div class="stat"><span class="muted small">LIGAS</span><strong>${c.domesticTitles}</strong></div><div class="stat"><span class="muted small">ACADEMIA</span><strong>${c.academy}</strong></div></div></section><section class="card"><h3>🏆 Historial competitivo</h3>${c.seasons.map(s=>`<p class="result">${s.season}: ${s.champion===c.name?'🏆 Campeón de Euroliga':s.finalist===c.name?'🥈 Finalista de Euroliga':s.acbChampion===c.name?'🏆 Campeón ACB':s.cupWinner===c.name?'🏆 Copa del Rey':'Final Four'}</p>`).join('')||'<p class="muted">Todavía no tiene grandes hitos registrados.</p>'}</section><section class="card"><h3>🌟 Talentos de la academia</h3><div class="database-list">${c.wonderkids.slice(0,12).map(p=>`<article><div><strong>${p.name}</strong><small>${p.country} · ${p.position} · ${p.status}<br>OVR ${p.ovr} · Potencial ${p.potential}</small></div><span>${p.grade}</span></article>`).join('')||'<p class="muted">No hay talentos archivados.</p>'}</div></section><section class="card"><h3>🔁 Mercado histórico</h3>${c.moves.slice(0,12).map(m=>`<p class="result">${m.season}: ${m.player} · ${m.from} → ${m.to}</p>`).join('')||'<p class="muted">No hay movimientos registrados.</p>'}</section><button data-view="encyclopedia" class="btn">← Volver a la Enciclopedia</button>`;
}


function balanceScreen(){
 const r=getBalanceReport(game),p=game.player;
 return `${playerHeader()}<section class="card"><span class="pill">NBA GLORY 1.2 · FASE 3</span><h2>Centro de equilibrio</h2><p class="muted">Progresión, salud, mercado e inteligencia de franquicias conectados al ciclo de temporada.</p><div class="grid"><div class="stat"><span class="muted small">VALOR DE MERCADO</span><strong>${formatMoney(r.marketValue)}</strong></div><div class="stat"><span class="muted small">SATISFACCIÓN</span><strong>${r.satisfaction}/100</strong></div><div class="stat"><span class="muted small">CONDICIÓN</span><strong>${r.condition}%</strong></div><div class="stat"><span class="muted small">FATIGA</span><strong>${r.fatigue}%</strong></div></div></section><section class="card"><h3>Informe deportivo</h3><div class="objective-list"><article><div><strong>Desgaste de carrera</strong><small>Aumenta con edad, carga y lesiones graves</small></div><span>${r.careerWear}%</span></article><article><div><strong>Historial médico</strong><small>Lesiones registradas en toda la carrera</small></div><span>${r.injuries}</span></article><article><div><strong>Promesa contractual</strong><small>Minutos acordados y rendimiento del rol</small></div><span>${p.contract?.promisedMinutes||'—'} min</span></article><article><div><strong>Franquicias con IA</strong><small>Contendientes, proyectos equilibrados y reconstrucciones</small></div><span>${r.teams}</span></article></div></section><button data-view="career" class="btn">← Volver a la carrera</button>`;
}
function systemScreen(){
 const health=diagnoseGame(game),meta=getSaveMeta(),backup=hasBackup();
 const size=(health.bytes/1024).toLocaleString("es-ES",{maximumFractionDigits:1});
 return `${playerHeader()}<section class="card encyclopedia-hero"><span class="pill">BETA 1.0a</span><h2>Estado del sistema</h2><p class="muted">Guardado transaccional, recuperación automática y control de integridad.</p></section>
 <section class="card"><h3>${health.ok?'✅ Partida estable':'⚠️ Revisión necesaria'}</h3><div class="grid"><div class="stat"><span class="muted small">TAMAÑO</span><strong>${size} KB</strong></div><div class="stat"><span class="muted small">TEMPORADAS</span><strong>${health.careerSeasons}</strong></div><div class="stat"><span class="muted small">JUGADORES IA</span><strong>${health.universePlayers}</strong></div><div class="stat"><span class="muted small">ARCHIVO</span><strong>${health.historicalSeasons}</strong></div></div>${health.issues.map(x=>`<p class="result">⚠ ${x}</p>`).join('')||'<p class="result">No se han detectado incoherencias estructurales.</p>'}</section>
 <section class="card"><h3>💾 Guardado protegido</h3><p class="result">${meta?`Último guardado: ${new Date(meta.savedAt).toLocaleString('es-ES')} · checksum ${meta.checksum}`:'La partida se guardará al realizar la siguiente acción.'}</p><p class="muted">${backup?'Existe una copia de seguridad válida para recuperación manual.':'La copia de seguridad se creará en el próximo guardado.'}</p><button id="exportSaveBtn" class="btn">Exportar partida</button>${backup?'<button id="restoreBackupBtn" class="btn secondary">Restaurar copia anterior</button>':''}<label class="btn secondary import-label">Importar partida<input id="importSaveInput" type="file" accept="application/json,.json" hidden></label></section>
 <section class="card"><h3>🛡️ Mejoras activas</h3><p class="pathway-achievement">✓ Escritura verificada antes de confirmar el guardado</p><p class="pathway-achievement">✓ Copia automática de la versión anterior</p><p class="pathway-achievement">✓ Recuperación si el archivo principal está dañado</p><p class="pathway-achievement">✓ Límites de historial para carreras de más de 30 temporadas</p><p class="pathway-achievement">✓ Migración automática de partidas 7.4</p></section><button data-view="career" class="btn">← Volver a la carrera</button>`;
}

  return {encyclopediaScreen:()=>{sync();return encyclopediaScreen();},playerBiographyScreen:()=>{sync();return playerBiographyScreen();},clubBiographyScreen:()=>{sync();return clubBiographyScreen();},balanceScreen:()=>{sync();return balanceScreen();},systemScreen:()=>{sync();return systemScreen();}};
}
