import { Random } from "../core/random-engine.js";
import { refreshPlayer, progressPlayer } from './player-engine.js';
import { createUniversalSimulationEngine } from './universal-simulation-engine.js';

const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const roll=(min,max)=>Math.floor(Random.next()*(max-min+1))+min;
const round1=n=>Math.round(n*10)/10;
const pick=a=>a[roll(0,a.length-1)];
const universalSimulation=createUniversalSimulationEngine();

const C=(id,name,conference,prestige,development,exposure,style)=>({id,name,conference,prestige,development,exposure,style});
export const COLLEGES=[
 C('DUKE','Duke Blue Devils','ACC',96,91,98,'Perímetro y spacing'),C('UNC','North Carolina Tar Heels','ACC',95,89,97,'Ritmo y transición'),C('UVA','Virginia Cavaliers','ACC',87,88,86,'Defensa y media pista'),C('LOU','Louisville Cardinals','ACC',88,87,89,'Atletismo'),C('CLEM','Clemson Tigers','ACC',82,86,82,'Equilibrio'),C('MIA','Miami Hurricanes','ACC',82,84,84,'Ataque abierto'),C('NCS','NC State Wolfpack','ACC',84,86,86,'Intensidad'),C('SYR','Syracuse Orange','ACC',86,84,88,'Zona y transición'),
 C('UK','Kentucky Wildcats','SEC',95,93,97,'Atletismo y transición'),C('FLA','Florida Gators','SEC',93,91,94,'Ritmo alto'),C('AUB','Auburn Tigers','SEC',92,90,94,'Defensa agresiva'),C('ALA','Alabama Crimson Tide','SEC',91,89,95,'Triple y ritmo'),C('TENN','Tennessee Volunteers','SEC',90,91,91,'Defensa física'),C('ARK','Arkansas Razorbacks','SEC',88,88,90,'Atletismo'),C('TAM','Texas A&M Aggies','SEC',86,87,85,'Rebote y dureza'),C('VAN','Vanderbilt Commodores','SEC',80,85,81,'Lectura de juego'),C('MISS','Ole Miss Rebels','SEC',81,84,82,'Perímetro'),C('UGA','Georgia Bulldogs','SEC',79,84,80,'Desarrollo'),
 C('MICH','Michigan Wolverines','Big Ten',94,91,95,'Juego completo'),C('MSU','Michigan State Spartans','Big Ten',93,92,94,'Defensa y dureza'),C('PUR','Purdue Boilermakers','Big Ten',94,90,95,'Juego interior'),C('ILL','Illinois Fighting Illini','Big Ten',90,89,91,'Volumen y protagonismo'),C('UCLA','UCLA Bruins','Big Ten',92,88,93,'Juego completo'),C('WIS','Wisconsin Badgers','Big Ten',87,88,86,'Media pista'),C('OSU','Ohio State Buckeyes','Big Ten',86,87,89,'Atletismo'),C('IOWA','Iowa Hawkeyes','Big Ten',84,86,85,'Ataque fluido'),C('NEB','Nebraska Cornhuskers','Big Ten',82,86,83,'Energía'),C('ORE','Oregon Ducks','Big Ten',87,88,90,'Transición'),C('IND','Indiana Hoosiers','Big Ten',89,87,91,'Tradición y tiro'),
 C('KU','Kansas Jayhawks','Big 12',96,92,98,'Juego completo'),C('HOU','Houston Cougars','Big 12',94,93,95,'Defensa élite'),C('ARI','Arizona Wildcats','Big 12',95,92,97,'Ritmo y talento'),C('ISU','Iowa State Cyclones','Big 12',91,91,92,'Presión defensiva'),C('TTU','Texas Tech Red Raiders','Big 12',88,89,88,'Defensa y spacing'),C('BAY','Baylor Bears','Big 12',90,89,92,'Guards y tiro'),C('BYU','BYU Cougars','Big 12',85,88,87,'Movimiento de balón'),C('UCF','UCF Knights','Big 12',79,84,80,'Atletismo'),C('CIN','Cincinnati Bearcats','Big 12',84,86,85,'Físico'),
 C('UCONN','UConn Huskies','Big East',97,94,98,'Defensa y competitividad'),C('STJ','St. John’s Red Storm','Big East',90,88,94,'Presión y ritmo'),C('VILL','Villanova Wildcats','Big East',92,90,94,'Fundamentos'),C('MARQ','Marquette Golden Eagles','Big East',89,89,92,'Perímetro'),C('CREI','Creighton Bluejays','Big East',88,90,90,'Spacing'),C('XAV','Xavier Musketeers','Big East',85,87,87,'Equilibrio'),
 C('GONZ','Gonzaga Bulldogs','WCC',93,94,94,'Fundamentos y lectura'),C('SMC','Saint Mary’s Gaels','WCC',87,91,86,'Media pista'),C('SCU','Santa Clara Broncos','WCC',78,85,79,'Desarrollo'),
 C('MEM','Memphis Tigers','AAC',88,87,91,'Atletismo'),C('VCU','VCU Rams','A-10',86,88,87,'Presión total'),C('SLU','Saint Louis Billikens','A-10',80,85,81,'Equilibrio'),C('NM','New Mexico Lobos','Mountain West',85,88,86,'Ritmo'),C('USU','Utah State Aggies','Mountain West',84,88,84,'Ejecución'),C('SDSU','San Diego State Aztecs','Mountain West',89,91,88,'Defensa'),
 C('TEX','Texas Longhorns','SEC',91,89,94,'Atletismo y exposición'),C('TCU','TCU Horned Frogs','Big 12',84,86,85,'Transición'),C('MIZZ','Missouri Tigers','SEC',82,85,83,'Ritmo'),C('SMU','SMU Mustangs','ACC',82,86,84,'Perímetro'),C('USF','South Florida Bulls','AAC',79,85,80,'Desarrollo'),C('LIB','Liberty Flames','C-USA',79,87,78,'Tiro'),C('AKR','Akron Zips','MAC',77,84,76,'Disciplina'),C('UNI','Northern Iowa Panthers','MVC',78,86,77,'Ejecución'),C('HOF','Hofstra Pride','CAA',76,84,75,'Guards'),C('HPT','High Point Panthers','Big South',76,85,75,'Ritmo'),C('MCN','McNeese Cowboys','Southland',77,85,77,'Presión'),C('YALE','Yale Bulldogs','Ivy',78,86,77,'IQ y tiro'),C('HOW','Howard Bison','MEAC',73,82,72,'Atletismo'),C('UMBC','UMBC Retrievers','America East',72,82,72,'Cinderella'),C('SIE','Siena Saints','MAAC',72,82,72,'Disciplina'),C('PRV','Prairie View A&M Panthers','SWAC',70,81,69,'Velocidad'),C('LIU','LIU Sharks','NEC',69,80,68,'Desarrollo')
];

const E=(id,name,country,league,europe,prestige,development,minutes,budget)=>({id,name,country,league,europe,prestige,development,minutes,budget});
export const EURO_CLUBS=[
 E('RMB','Real Madrid','España','Liga ACB','EuroLeague',98,92,65,98),E('BAR','FC Barcelona','España','Liga ACB','EuroLeague',96,91,68,96),E('VAL','Valencia Basket','España','Liga ACB','EuroLeague',89,90,79,87),E('BAS','Baskonia','España','Liga ACB','EuroLeague',90,92,80,88),
 E('PAO','Panathinaikos','Grecia','Greek Basket League','EuroLeague',97,90,70,97),E('OLY','Olympiacos','Grecia','Greek Basket League','EuroLeague',97,92,72,96),E('FEN','Fenerbahçe','Turquía','BSL','EuroLeague',96,91,72,96),E('EFS','Anadolu Efes','Turquía','BSL','EuroLeague',94,89,75,94),E('MON','AS Monaco','Mónaco','LNB Élite','EuroLeague',94,88,75,96),E('PAR','Paris Basketball','Francia','LNB Élite','EuroLeague',89,95,84,89),E('MIL','Olimpia Milano','Italia','Lega Basket','EuroLeague',93,88,73,95),E('VIR','Virtus Bologna','Italia','Lega Basket','EuroLeague',91,89,77,91),E('BAY','Bayern Munich','Alemania','BBL','EuroLeague',91,91,77,93),E('ASV','ASVEL Villeurbanne','Francia','LNB Élite','EuroLeague',85,91,84,84),E('MAC','Maccabi Tel Aviv','Israel','Winner League','EuroLeague',93,88,76,91),E('ZAL','Žalgiris Kaunas','Lituania','LKL','EuroLeague',91,94,82,85),E('CZV','Crvena zvezda','Serbia','ABA League','EuroLeague',91,92,78,87),E('PARZ','Partizan Belgrade','Serbia','ABA League','EuroLeague',93,92,76,90),E('HAP','Hapoel Tel Aviv','Israel','Winner League','EuroLeague',88,89,80,90),E('DUB','Dubai Basketball','EAU','ABA League','EuroLeague',88,87,82,98),
 E('JOV','Joventut Badalona','España','Liga ACB','EuroCup',87,96,89,80),E('GCA','Gran Canaria','España','Liga ACB','EuroCup',86,91,86,83),E('MAN','BAXI Manresa','España','Liga ACB','EuroCup',82,94,92,76),E('CED','Cedevita Olimpija','Eslovenia','ABA League','EuroCup',84,92,88,78),E('BUD','Budućnost','Montenegro','ABA League','EuroCup',83,89,87,78),E('VEN','Reyer Venezia','Italia','Lega Basket','EuroCup',84,88,85,82),E('TRE','Dolomiti Energia Trento','Italia','Lega Basket','EuroCup',80,91,90,75),E('TUR','Türk Telekom','Turquía','BSL','EuroCup',84,88,84,84),E('BAH','Bahçeşehir Koleji','Turquía','BSL','EuroCup',85,89,84,87),E('ARI','Aris Thessaloniki','Grecia','Greek Basket League','EuroCup',83,90,88,77),E('CLU','U-BT Cluj-Napoca','Rumanía','Liga Națională','EuroCup',80,91,91,73),E('ULM','ratiopharm Ulm','Alemania','BBL','EuroCup',82,96,93,76),E('HAM','Hamburg Towers','Alemania','BBL','EuroCup',76,92,94,72),E('BES','Beşiktaş','Turquía','BSL','EuroCup',87,88,84,88),E('LON','London Lions','Reino Unido','British League','EuroCup',77,89,92,74),E('LIE','Lietkabelis','Lituania','LKL','EuroCup',78,91,91,72),E('WRO','Śląsk Wrocław','Polonia','PLK','EuroCup',76,88,91,70),E('BOU','JL Bourg','Francia','LNB Élite','EuroCup',82,93,91,78),E('BESI','Brescia','Italia','Lega Basket','EuroCup',82,88,87,80),E('HAPJ','Hapoel Jerusalem','Israel','Winner League','EuroCup',86,89,85,86)
];

export const GLEAGUE_TEAMS=['Austin Spurs','Birmingham Squadron','Capital City Go-Go','College Park Skyhawks','Delaware Blue Coats','Grand Rapids Gold','Greensboro Swarm','Iowa Wolves','Long Island Nets','Maine Celtics','Memphis Hustle','Mexico City Capitanes','Motor City Cruise','Oklahoma City Blue','Osceola Magic','Raptors 905','Rio Grande Valley Vipers','Rip City Remix','Salt Lake City Stars','San Diego Clippers','Santa Cruz Warriors','Sioux Falls Skyforce','South Bay Lakers','Stockton Kings','Texas Legends','Valley Suns','Westchester Knicks','Windy City Bulls','Wisconsin Herd'];
export const NATIONAL_TEAMS=['España','Estados Unidos','Francia','Serbia','Canadá','Alemania','Grecia','Lituania','Italia','Australia','Eslovenia','Turquía','Brasil','Argentina','Puerto Rico','Croacia','Letonia','Japón'];

export function migratePathway(game){
 if(!game?.player)return game; const p=game.player;
 p.nationality??='España';
 p.preDraft??={stage:game.phase==='draft'?'draftNight':'highSchool',route:null,year:0,stock:50,projection:'Segunda ronda',history:[],awards:[],interviews:[],offers:[],mockPick:45,declared:false,currentProgram:null,stats:null,trophies:[]};
 const pd=p.preDraft; pd.version=3; pd.contracts??=[];pd.international??={caps:0,medals:[],awards:[],history:[],reputation:35};pd.clubOffers??=[];pd.careerGoal??='nba';pd.marketValue??=250000;pd.salary??=0;pd.seasonIndex??=0;
 return game;
}
function updateProjection(pd){pd.mockPick=clamp(Math.round(61-pd.stock*.58),1,60);pd.projection=pd.mockPick<=5?'Top 5':pd.mockPick<=14?'Lottery':pd.mockPick<=30?'Primera ronda':pd.mockPick<=45?'Segunda ronda alta':'Segunda ronda';}
function adjustStock(pd,delta,reason){pd.stock=clamp(round1(pd.stock+delta),15,99);pd.history.push({type:'stock',delta,reason,stock:pd.stock});updateProjection(pd);}
function boostAttributes(p,amount){progressPlayer(p,{amount,severeInjury:false});refreshPlayer(p);}
export function startPathway(game){migratePathway(game);game.player.preDraft.stage='highSchool';game.phase='pathway';return game;}
function maybeInternationalSummer(game,level){const p=game.player,pd=p.preDraft,year=game.season+pd.seasonIndex;const eligible=p.ovr+pd.international.reputation/8+roll(-8,8);if(eligible<74)return null;const type=year%4===0?'Juegos Olímpicos':year%4===2?'Mundial FIBA':p.nationality==='Estados Unidos'?'AmeriCup':'EuroBasket';const finish=eligible>92&&roll(1,100)<45?'Oro':eligible>84&&roll(1,100)<55?'Plata':eligible>78?'Bronce':'Cuartos de final';const medal=['Oro','Plata','Bronce'].includes(finish)?finish:null;pd.international.caps+=roll(5,9);pd.international.reputation=clamp(pd.international.reputation+(medal?10:4),0,100);if(medal)pd.international.medals.push({type,medal,year});const award=eligible>91?'MVP del torneo':eligible>84?'Mejor quinteto':null;if(award)pd.international.awards.push({type,award,year});const item={type:'international',tournament:type,finish,award,year,nation:p.nationality};pd.international.history.push(item);pd.history.push(item);pd.trophies.push(`${p.nationality}: ${finish} en ${type}`);adjustStock(pd,medal==='Oro'?5:medal?3:1,`${type} con ${p.nationality}`);return `${type}: ${p.nationality} termina con ${finish}${award?` · ${award}`:''}.`;}
function highSchoolSeason(game){const p=refreshPlayer(game.player),pd=p.preDraft;const dominance=clamp((p.ovr-62)*1.1+roll(-6,8),45,98);const stats={ppg:round1(12+dominance*.18),rpg:round1(3+(p.position==='C'||p.position==='PF'?dominance*.09:dominance*.045)),apg:round1(1+(p.position==='PG'?dominance*.095:dominance*.04)),wins:roll(20,31)};pd.stats=stats;pd.offers=COLLEGES.map(c=>({...c,interest:clamp(Math.round(c.development*.35+c.exposure*.25+dominance*.45+roll(-12,8)),45,99)})).sort((a,b)=>b.interest-a.interest);adjustStock(pd,(dominance-65)/5,'Temporada de instituto');pd.history.push({type:'highSchool',season:game.season,stats,headline:dominance>82?'All-American y estrella nacional':dominance>70?'Prospecto nacional en ascenso':'Talento regional con margen'});pd.stage='recruiting';game.lastSummary=`Instituto: ${stats.ppg} PPG, ${stats.rpg} RPG y ${stats.apg} APG. Tienes ${pd.offers.length} programas disponibles.`;}
function chooseRoute(game,choice){const pd=game.player.preDraft;if(choice==='route_college'){pd.route='college';pd.stage='collegeSelect';game.lastSummary='Has elegido NCAA: reclutamiento, conferencia y March Madness.';return;}if(choice==='route_europe'){pd.route='europe';pd.stage='europeSelect';game.lastSummary='Has elegido Europa: contratos, ligas, copas y competiciones continentales.';return;}pd.route='gLeague';pd.currentProgram={id:'GL',name:pick(GLEAGUE_TEAMS),league:'G League',development:93,prestige:84,minutes:91};pd.stage='preDraftSeason';game.lastSummary=`Firmas con ${pd.currentProgram.name} para jugar contra profesionales.`;}
function selectProgram(game,choice){const pd=game.player.preDraft;const source=pd.route==='college'?COLLEGES:EURO_CLUBS;const id=choice.replace('program_','');pd.currentProgram=source.find(x=>x.id===id)||source[0];pd.stage='preDraftSeason';if(pd.route==='europe'){pd.salary=Math.round((120000+pd.currentProgram.budget*14000+pd.stock*8000)/10000)*10000;pd.contracts.push({club:pd.currentProgram.name,years:roll(1,3),salary:pd.salary});}pd.history.push({type:'commitment',route:pd.route,program:pd.currentProgram.name});game.lastSummary=`Te incorporas a ${pd.currentProgram.name}${pd.salary?` con un salario de ${pd.salary.toLocaleString('es-ES')} €`:''}.`;}
function simulateCollege(game){const p=refreshPlayer(game.player),pd=p.preDraft,c=pd.currentProgram;const role=clamp(48+(p.ovr-68)*4+roll(-10,12),30,96),games=roll(29,34);const sim=universalSimulation.simulatePlayerCompetition({competition:'ncaa',player:p,team:{name:c.name,strength:c.prestige},coach:{name:c.name,development:c.development,trust:c.exposure-10},minutes:round1(16+role*.18),chemistry:c.development-10,games,isRookie:pd.year===0});const stats={...sim.stats,games,wins:sim.teamResult.wins,simulationEngine:sim.simulationEngine,competitionProfile:sim.competitionProfile};const march=sim.teamResult.champion?'Campeón NCAA':sim.teamResult.roundsWon>=4?'Final Four':sim.teamResult.roundsWon>=3?'Elite Eight':sim.teamResult.roundsWon>=2?'Sweet Sixteen':sim.teamResult.playoffs?'March Madness':'Fuera del torneo';const award=sim.awards.allNba==='First Team'?'All-American First Team':sim.awards.allNba?'All-Conference':'Freshman destacado';pd.stats=stats;pd.trophies.push(march);pd.awards.push(award);pd.year++;pd.seasonIndex++;p.age++;adjustStock(pd,(stats.ppg-12)*.65+(c.exposure-80)*.08+(march==='Campeón NCAA'?8:march==='Final Four'?4:0),`${c.name}: ${award}`);boostAttributes(p,c.development>=90?2:1);pd.history.push({type:'collegeSeason',program:c.name,conference:c.conference,stats,competition:march,award,simulationEngine:sim.simulationEngine});const intl=maybeInternationalSummer(game,'U23');pd.stage='seasonDecision';game.lastSummary=`${c.name}: ${stats.ppg} PPG · ${march} · ${award}.${intl?' '+intl:''}`;}
function simulateEurope(game){const p=refreshPlayer(game.player),pd=p.preDraft,club=pd.currentProgram;const role=clamp((club.minutes||75)+(p.ovr-72)*2+roll(-12,9),35,98),games=roll(30,34);const sim=universalSimulation.simulatePlayerCompetition({competition:'euroleague',player:p,team:{name:club.name,strength:club.prestige},coach:{name:club.name,development:club.development,trust:club.minutes},minutes:round1(9+role*.22),chemistry:club.development-8,games});const stats={...sim.stats,games,leagueWins:clamp(sim.teamResult.wins+roll(-2,3),8,32),europeWins:sim.teamResult.wins,simulationEngine:sim.simulationEngine,competitionProfile:sim.competitionProfile};const leagueResult=stats.leagueWins>=28?`Campeón de ${club.league}`:stats.leagueWins>=24?`Finalista de ${club.league}`:`Playoffs de ${club.league}`;const cup=roll(1,100)<=35?`Campeón de Copa (${club.country})`:`Copa: ${roll(1,2)===1?'semifinales':'cuartos'}`;const euro=sim.teamResult.champion?'Campeón de EuroLeague':sim.teamResult.roundsWon>=2?'Final Four de EuroLeague':sim.teamResult.playoffs?'Playoffs de EuroLeague':'Temporada regular EuroLeague';const award=sim.awards.mvp?'MVP de la competición':stats.ppg>=13?'Rising Star europeo':'Prospecto profesional';pd.stats=stats;pd.trophies.push(leagueResult,cup,euro);pd.awards.push(award);pd.year++;pd.seasonIndex++;p.age++;pd.marketValue=Math.round((pd.stock*18000+p.ovr*22000+club.prestige*8000)/10000)*10000;adjustStock(pd,(stats.ppg-7)*.75+(club.prestige-80)*.09+(euro.includes('Campeón')?8:euro.includes('Final Four')?5:1),`${club.name}: ${award}`);boostAttributes(p,club.development>=92?2:1);pd.history.push({type:'europeSeason',club:club.name,league:club.league,europe:club.europe,stats,leagueResult,cup,euro,award,salary:pd.salary,simulationEngine:sim.simulationEngine});const intl=maybeInternationalSummer(game,'senior');pd.clubOffers=EURO_CLUBS.filter(x=>x.id!==club.id).map(x=>({...x,offerSalary:Math.round((pd.marketValue*(.65+x.budget/180)+roll(-80000,120000))/10000)*10000,interest:clamp(Math.round(pd.stock*.55+p.ovr*.35+x.development*.1+roll(-18,8)),20,99)})).sort((a,b)=>b.interest-a.interest).slice(0,10);pd.stage='seasonDecision';game.lastSummary=`${club.name}: ${stats.ppg} PPG · ${leagueResult} · ${euro} · ${award}.${intl?' '+intl:''}`;}
function simulateProSeason(game){const p=refreshPlayer(game.player),pd=p.preDraft,games=roll(42,50);const sim=universalSimulation.simulatePlayerCompetition({competition:'gleague',player:p,team:{name:pd.currentProgram.name,strength:76},coach:{name:pd.currentProgram.name,development:88,trust:82},minutes:round1(24+roll(0,9)),chemistry:75,games});const stats={...sim.stats,games,simulationEngine:sim.simulationEngine,competitionProfile:sim.competitionProfile};pd.stats=stats;pd.year++;pd.seasonIndex++;p.age++;adjustStock(pd,(stats.ppg-12)*.8+4,'Temporada profesional G League');boostAttributes(p,2);pd.history.push({type:'gLeagueSeason',team:pd.currentProgram.name,stats,simulationEngine:sim.simulationEngine});const intl=maybeInternationalSummer(game,'senior');pd.stage='seasonDecision';game.lastSummary=`${pd.currentProgram.name}: ${stats.ppg} PPG en G League.${intl?' '+intl:''}`;}
function changeEuropeClub(game,choice){const pd=game.player.preDraft,id=choice.replace('transfer_',''),offer=pd.clubOffers.find(x=>x.id===id);if(!offer)return;pd.currentProgram=offer;pd.salary=offer.offerSalary;pd.contracts.push({club:offer.name,years:roll(1,3),salary:pd.salary});pd.stage='preDraftSeason';pd.history.push({type:'transferEurope',club:offer.name,salary:pd.salary});game.lastSummary=`Fichas por ${offer.name}: ${pd.salary.toLocaleString('es-ES')} € por temporada.`;}
function runCombine(game){const p=game.player,pd=p.preDraft;const athletic=round1(((p.attributes.speed||70)+(p.attributes.strength||70))/2+roll(-5,5)),shooting=round1(((p.attributes.threePoint||70)+(p.attributes.midRange||70))/2+roll(-5,5)),scrimmage=round1((p.ovr+p.attributes.iq)/2+roll(-6,6)),total=round1(athletic*.3+shooting*.3+scrimmage*.4);adjustStock(pd,(total-72)/3,'NBA Draft Combine');pd.combine={athletic,shooting,scrimmage,total};pd.stage='interviews';game.lastSummary=`Combine: ${total}/100. ${total>=75?'Los scouts quedan satisfechos.':'Tu stock queda bajo presión.'}`;}
function runInterview(game,choice){const pd=game.player.preDraft;const profiles={leader:{label:'Liderazgo',delta:3},humble:{label:'Humildad y trabajo',delta:2.5},confident:{label:'Confianza de estrella',delta:1.5},international:{label:'Madurez internacional',delta:pd.route==='europe'?4:1}};const r=profiles[choice]||profiles.humble;adjustStock(pd,r.delta+roll(-1,2),`Entrevista: ${r.label}`);pd.interviews.push(r.label);pd.stage='mockDraft';game.lastSummary=`Las entrevistas refuerzan tu imagen: ${r.label}.`;}
function finalizeMock(game){const pd=game.player.preDraft;updateProjection(pd);pd.stage='draftNight';pd.declared=true;game.phase='draft';game.lastSummary=`Mock Draft final: pick ${pd.mockPick} (${pd.projection}).`;}
export function advancePathway(game,choice){migratePathway(game);const pd=game.player.preDraft;if(pd.stage==='highSchool')highSchoolSeason(game);else if(pd.stage==='recruiting')chooseRoute(game,choice);else if(pd.stage==='collegeSelect'||pd.stage==='europeSelect')selectProgram(game,choice);else if(pd.stage==='preDraftSeason')pd.route==='college'?simulateCollege(game):pd.route==='europe'?simulateEurope(game):simulateProSeason(game);else if(pd.stage==='seasonDecision'){if(choice.startsWith('transfer_'))changeEuropeClub(game,choice);else if(choice==='stay_one_more'){pd.stage='preDraftSeason';game.lastSummary=`Continúas una temporada más en ${pd.currentProgram.name}.`;}else if(choice==='europe_career'){pd.careerGoal='europe';pd.stage='preDraftSeason';game.lastSummary='Has decidido construir tu leyenda en Europa. El Draft seguirá disponible en próximos veranos.';}else{pd.stage='combine';game.lastSummary='Te declaras elegible para el NBA Draft.';}}else if(pd.stage==='combine')runCombine(game);else if(pd.stage==='interviews')runInterview(game,choice);else if(pd.stage==='mockDraft')finalizeMock(game);return game;}
export function getPathwayOptions(game){migratePathway(game);const pd=game.player.preDraft;if(pd.stage==='highSchool')return[{id:'play_highschool',title:'Jugar temporada de instituto',text:'Construye reputación, stock y ofertas.'}];if(pd.stage==='recruiting')return[{id:'route_college',title:'🇺🇸 NCAA',text:`${COLLEGES.length} universidades, conferencias y March Madness.`},{id:'route_europe',title:'🇪🇺 Europa',text:`${EURO_CLUBS.length} clubes, ligas, copas, EuroLeague y EuroCup.`},{id:'route_gLeague',title:'🏀 G League',text:'Carrera profesional USA, salario y escaparate NBA.'}];if(pd.stage==='collegeSelect')return pd.offers.map(x=>({id:`program_${x.id}`,title:`${x.name} · ${x.conference}`,text:`Interés ${x.interest}% · ${x.style} · desarrollo ${x.development}`}));if(pd.stage==='europeSelect')return EURO_CLUBS.map(x=>({id:`program_${x.id}`,title:`${x.name} · ${x.country}`,text:`${x.league} · ${x.europe} · desarrollo ${x.development} · minutos ${x.minutes}`}));if(pd.stage==='preDraftSeason')return[{id:'play_season',title:pd.route==='europe'?'Jugar temporada europea':pd.route==='college'?'Jugar temporada NCAA':'Jugar temporada G League',text:pd.route==='europe'?`Liga, Copa y ${pd.currentProgram.europe}.`:'Desarrolla tu juego y mejora el stock.'}];if(pd.stage==='seasonDecision'){const base=[{id:'declare_draft',title:'Declararme para el NBA Draft',text:`Proyección: ${pd.projection} · pick ${pd.mockPick}.`},{id:'stay_one_more',title:pd.route==='europe'?'Renovar y seguir en Europa':'Jugar un año más',text:'Más desarrollo, pero también riesgo.'}];if(pd.route==='europe'){base.push({id:'europe_career',title:'Construir carrera completa en Europa',text:'No renuncias al Draft: decides priorizar títulos, contratos y legado europeo.'});pd.clubOffers.slice(0,6).forEach(x=>base.push({id:`transfer_${x.id}`,title:`Fichar por ${x.name}`,text:`Oferta ${x.offerSalary.toLocaleString('es-ES')} € · ${x.europe} · interés ${x.interest}%`}));}return base;}if(pd.stage==='combine')return[{id:'run_combine',title:'Participar en el NBA Draft Combine',text:'Pruebas atléticas, tiro y cinco contra cinco.'}];if(pd.stage==='interviews')return[{id:'leader',title:'“Quiero liderar una franquicia”',text:'Ambición y liderazgo.'},{id:'humble',title:'“Me ganaré cada minuto”',text:'Trabajo y humildad.'},{id:'confident',title:'“Soy el mejor de esta clase”',text:'Confianza y presión.'},{id:'international',title:'“Mi experiencia profesional me preparó”',text:'Madurez NCAA, G League o europea.'}];if(pd.stage==='mockDraft')return[{id:'finalize_mock',title:'Publicar Mock Draft final',text:'Descubre tu rango definitivo.'}];return[];}
export function getPathwayTitle(game){const s=game.player.preDraft.stage;return({highSchool:'Instituto',recruiting:'Elige tu camino',collegeSelect:'Reclutamiento NCAA',europeSelect:'Mercado europeo',preDraftSeason:'Temporada de desarrollo',seasonDecision:'Decisión de carrera',combine:'NBA Draft Combine',interviews:'Entrevistas',mockDraft:'Mock Draft final',draftNight:'Noche del Draft'})[s]||'Road to Glory';}
